export const Products=[
    {
        img_product:require('./../../asset/image/product-1.png'),
        name_product:'NIKE FREE RN 2019 ID',
        price_old:'$120.00',
        price_sale:'$80.00',
        rate_sale:null,
        star:3,
    },
    {
        img_product:require('./../../asset/image/product-2.png'),
        name_product:'NIKE FREE RN 2019 ID',
        price_old:'$120.00',
        price_sale:'$80.00',
        rate_sale:50,
        star:4,
    },
    {
        img_product:require('./../../asset/image/product-3.png'),
        name_product:'NIKE FREE RN 2019 ID',
        price_old:'$120.00',
        price_sale:'$80.00',
        rate_sale:null,
        star:5,
    },
    {
        img_product:require('./../../asset/image/product-4.png'),
        name_product:'NIKE FREE RN 2019 ID',
        price_old:'$120.00',
        price_sale:'$80.00',
        rate_sale:null,
        star:4,
    },
    {
        img_product:require('./../../asset/image/product-5.png'),
        name_product:'NIKE FREE RN 2019 ID',
        price_old:'$120.00',
        price_sale:'$80.00',
        rate_sale:null,
        star:4,
    },
    {
        img_product:require('./../../asset/image/product-6.png'),
        name_product:'NIKE FREE RN 2019 ID',
        price_old:'$120.00',
        price_sale:'$80.00',
        rate_sale:30,
        star:4,
    },
    {
        img_product:require('./../../asset/image/product-7.png'),
        name_product:'NIKE FREE RN 2019 ID',
        price_old:'$120.00',
        price_sale:'$80.00',
        rate_sale:null,
        star:5,
    },
    {
        img_product:require('./../../asset/image/product-8.png'),
        name_product:'NIKE FREE RN 2019 ID',
        price_old:'$120.00',
        price_sale:'$80.00',
        rate_sale:10,
        star:4,
    },
]